owner: sanbi-uwc
remote_repository_url: https://github.com/pvanheus/polio_report
categories:
 - Sequence Analysis
repositories:
  assess_poliovirus_alignment:
    description: Assess the input from alignment against poliovirus reference genomes
    include:
      - assess_poliovirus_alignment.xml
      - assess_alignment.py

  summarize_poliovirus_alignment:
    description: Summarize poliovirus alignment reports
    include:
      - summarize_poliovirus_alignment.xml
      - summarize_alignment.py